apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-mysql-0
  namespace: joe
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 10Gi
