apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf-cm
  namespace: joe
data:
  default.conf: |
    server {
        listen       80;
        location / {
          proxy_pass http://wordpress-svc.joe;
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $remote_addr;
          proxy_set_header X-Forwarded-Proto https;
        }
    }
