apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: joe
  labels:
    service: nginx
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30002
  selector:
    service: nginx
