apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx
  namespace: joe
spec:
  replicas: 3
  selector:
    matchLabels:
      service: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        service: nginx
    spec:
      volumes:
        - name: nginx-conf-cm
          configMap:
            name: nginx-conf-cm
      containers:
      - name: nginx
        image: nginx:1.11.5
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
         requests:
            cpu: 50m
            memory: 100m
         limits:
            cpu: 100m
            memory: 256Mi
        # envFrom:
        #   - configMapRef:
        #       name: env
        volumeMounts:
          - name: nginx-conf-cm
            readOnly: true
            mountPath: /etc/nginx/conf.d
        #    subPath: default.conf
