apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
  namespace: joe
  labels:
     app: wordpress
spec:
  type: ClusterIP
#  loadBalancerSourceRanges:
#    - "116.241.212.54/32"
  #externalTrafficPolicy: Local
  ports:
  - port: 80
    # name: web
    protocol: TCP
    targetPort: 80
  # - port: 443
  #   name: https
  #   protocol: TCP
  #   targetPort: 443
  selector:
    app: wordpress
    test: testwordpress #吃到wp-dp-pod
